default: &default
  executor: Hako
  executor_options:
    hako_dir: /home/k0kubun/hako_repo
    hako_env:
      ACCESS_TOKEN: token
    yaml_dir: /yamls

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
